### ISSUE TITLE
Widget fails to install due to a timer issue 

### ISSUE THREAD

**Issue by uric** [CloudifySource/cloudify-widget#22]
When clicking "Play" on any recipe (even recipes that worked before), nothing happens. Log indicates the following issue: 

236514176 [play-akka.actor.actions-dispatcher-69] INFO  application - Downloading recipe: https://dl.dropbox.com/u/5682483/mongodb.zip to /root/play-2.0.4/cloudify-widget/recipes/1674bab7-09b5-4fe1-b50d-7708320a2833/3999662508835728/mongodb.zip
236515393 [play-akka.actor.actions-dispatcher-69] INFO  application - Starting to extract recipe to: /root/play-2.0.4/cloudify-widget/recipes/1674bab7-09b5-4fe1-b50d-7708320a2833/3999662508835728/mongodb.zip
236515393 [play-akka.actor.actions-dispatcher-69] INFO  application - Extracting: mongodb/mongod-service.groovy
236515394 [play-akka.actor.actions-dispatcher-69] INFO  application - Extracting: __MACOSX/mongodb/._mongod-service.groovy
236515395 [play-akka.actor.actions-dispatcher-69] INFO  application - Extracting: mongodb/mongod-service.properties
236515395 [play-akka.actor.actions-dispatcher-69] INFO  application - Extracting: __MACOSX/mongodb/._mongod-service.properties
236515395 [play-akka.actor.actions-dispatcher-69] INFO  application - Extracting: mongodb/mongod_install.groovy
236515396 [play-akka.actor.actions-dispatcher-69] INFO  application - Extracting: __MACOSX/mongodb/._mongod_install.groovy
236515397 [play-akka.actor.actions-dispatcher-69] INFO  application - Extracting: mongodb/mongod_start.groovy
236515397 [play-akka.actor.actions-dispatcher-69] INFO  application - Extracting: __MACOSX/mongodb/._mongod_start.groovy
236515398 [play-akka.actor.actions-dispatcher-69] INFO  application - Extracting: mongodb/mongodb.png
236515398 [play-akka.actor.actions-dispatcher-69] INFO  application - Extracting: __MACOSX/mongodb/._mongodb.png
236515399 [play-akka.actor.actions-dispatcher-69] INFO  application - Extracting: mongodb/README.md
236515400 [play-akka.actor.actions-dispatcher-69] INFO  application - Extracting: __MACOSX/mongodb/._README.md
236515400 [play-akka.actor.actions-dispatcher-69] INFO  application - Extracting: mongodb/usmlib/mongo-java-driver-2.6.5.jar
236515405 [play-akka.actor.actions-dispatcher-69] INFO  application - Extracting: __MACOSX/mongodb/usmlib/._mongo-java-driver-2.6.5.jar
236515405 [play-akka.actor.actions-dispatcher-69] INFO  application - Extracting: __MACOSX/mongodb/._usmlib
236515406 [play-akka.actor.actions-dispatcher-69] INFO  application - Extracting: __MACOSX/._mongodb
236515413 [play-akka.actor.actions-dispatcher-69] INFO  application - This server 15.185.111.23 was scheduled for destroy after: 3599997 ms
236515415 [play-akka.actor.actions-dispatcher-69] ERROR application - 

! @6cjgpf6e6 - Internal server error, for request [POST /widget/start?apiKey=1674bab7-09b5-4fe1-b50d-7708320a2833] ->

play.core.ActionInvoker$$anonfun$receive$1$$anon$1: Execution exception [[IllegalStateException: Timer already cancelled.]]
    at play.core.ActionInvoker$$anonfun$receive$1.apply(Invoker.scala:134) [play_2.9.1.jar:2.0.4]
    at play.core.ActionInvoker$$anonfun$receive$1.apply(Invoker.scala:115) [play_2.9.1.jar:2.0.4]
    at akka.actor.Actor$class.apply(Actor.scala:318) [akka-actor.jar:2.0.2]
    at play.core.ActionInvoker.apply(Invoker.scala:113) [play_2.9.1.jar:2.0.4]
    at akka.actor.ActorCell.invoke(ActorCell.scala:626) [akka-actor.jar:2.0.2]
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:197) [akka-actor.jar:2.0.2]
    at akka.dispatch.Mailbox.run(Mailbox.scala:179) [akka-actor.jar:2.0.2]
    at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:516) [akka-actor.jar:2.0.2]
    at akka.jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:259) [akka-actor.jar:2.0.2]
    at akka.jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) [akka-actor.jar:2.0.2]
    at akka.jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1479) [akka-actor.jar:2.0.2]
    at akka.jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) [akka-actor.jar:2.0.2]
Caused by: java.lang.IllegalStateException: Timer already cancelled.
    at java.util.Timer.sched(Timer.java:354) ~[na:1.6.0_32]
    at java.util.Timer.schedule(Timer.java:170) ~[na:1.6.0_32]
    at beans.ExpireServersCollectorImpl.scheduleToDestroy(ExpireServersCollectorImpl.java:47) ~[classes/:na]
    at beans.ServerPoolImpl.get(ServerPoolImpl.java:140) ~[classes/:na]
    at beans.WidgetServerImpl.deploy(WidgetServerImpl.java:68) ~[classes/:na]
    at controllers.Application.start(Application.java:38) ~[classes/:2.0.4]
    at Routes$$anonfun$routes$1$$anonfun$apply$1$$anonfun$apply$2.apply(routes_routing.scala:96) ~[classes/:na]
    at Routes$$anonfun$routes$1$$anonfun$apply$1$$anonfun$apply$2.apply(routes_routing.scala:96) ~[classes/:na]
    at play.core.Router$HandlerInvoker$$anon$5$$anon$1.invocation(Router.scala:1090) ~[play_2.9.1.jar:2.0.4]
    at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:33) ~[play_2.9.1.jar:2.0.4]
    at play.GlobalSettings$1.call(GlobalSettings.java:57) ~[play_2.9.1.jar:2.0.4]
    at play.core.j.JavaAction$class.apply(JavaAction.scala:74) ~[play_2.9.1.jar:2.0.4]
    at play.core.Router$HandlerInvoker$$anon$5$$anon$1.apply(Router.scala:1089) ~[play_2.9.1.jar:2.0.4]
    at play.core.ActionInvoker$$anonfun$receive$1$$anonfun$6.apply(Invoker.scala:126) ~[play_2.9.1.jar:2.0.4]
    at play.core.ActionInvoker$$anonfun$receive$1$$anonfun$6.apply(Invoker.scala:126) ~[play_2.9.1.jar:2.0.4]
    at play.utils.Threads$.withContextClassLoader(Threads.scala:17) ~[play_2.9.1.jar:2.0.4]
    at play.core.ActionInvoker$$anonfun$receive$1.apply(Invoker.scala:125) [play_2.9.1.jar:2.0.4]
    ... 11 common frames omitted

**Comment by guy-mograbi-at-gigaspaces** [comment]
fixed in ba1a7ae274c5899f57d1b50c26908449592cec13
